apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wmbjmv566-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-45baf196d1.246r.p3.openshiftapps.com/rhtap/rhtap-qe-java-quarkus:b5ac2a9d1ad740c2319999093a6ae82cc14576f8@sha256:5c4413d8e7bba0e93b0a6cf2aaeb0168b645b33c26e0a270d792c660eab3717e
          name: container-image
